language: node_js

node_js:
  - 0.8

before_script:
  - "make deps-all"
  - "mysql -e 'create database test_db;'"
  - "psql -c 'create database test_db;' -U postgres"

script:
  - "NODE_ENV=travis make tests"

notifications:
  email: false
  
services:
  - rabbitmq
  - mongodb