
/* Framework Regular Expressions */

module.exports = {
  
  relPath: /^\.\//,
  absPath: /^\//,
  isPath: /\//g,
  jsFile: /\.js$/i,
  dotFile: /^\./,
  validRegex: /^\/\^(.+)\$\//,
  singleParam: /^\/([a-z0-9\-:]+)?$/i,
  fileWithExtension: /\.[a-z][a-z0-9]+$/i,
  htmlFile: /\.htm(l)?$/i,
  hasSlash: /\//g,
  multipleSlashes: /\/+/g,
  startsWithSlash: /^\//,
  startsWithSlashes: /^\/+/,
  restrictedView: /^#\/?/,
  layoutView: /^@\/?/,
  startsWithUnderscore: /^_/,
  startOrEndSlash: /(^\/|\/$)/g,
  startOrEndRegex: /(^\^|\$$)/g,
  endingSlash: /\/$/,
  regExpChars: /(\^|\$|\\|\.|\*|\+|\?|\(|\)|\[|\]|\{|\}|\||\/)/g,
  controllerAlias: /^\/(.*?)\//,
  headerFilter: /^__([a-z][a-z\-]+[a-z])__$/,
  integer: /^[0-9]+$/,
  float: /^\d+\.\d+$/,
  number: /^\d+(\.\d+)?$/,
  "null": /^null$/i,
  boolean: /^(true|false)$/i,
  binary: /^(0|1)$/,
  digit: /^\d$/,
  alpha: /^[a-z]+$/i,
  alpha_spaces: /^[a-z ]+$/i,
  alpha_dashes: /^[a-z\-]+$/i,
  alpha_underscores: /^[a-z_]+$/i,
  alpha_spaces_underscores: /^[a-z _]+$/i,
  alpha_dashes_underscores: /^[a-z\-_]+$/i,
  alpha_lower: /^[a-z]+$/,
  alpha_lower_spaces: /^[a-z ]+$/,
  alpha_lower_dashes: /^[a-z\-]+$/,
  alpha_lower_underscores: /^[a-z_]+$/,
  alpha_lower_spaces_underscores: /^[a-z _]+$/,
  alpha_lower_dashes_underscores: /^[a-z\-_]+$/,
  alpha_upper: /^[A-Z]+$/,
  alpha_upper_spaces: /^[A-Z ]+$/,
  alpha_upper_dashes: /^[A-Z\-]+$/,
  alpha_upper_underscores: /^[A-Z_]+$/,
  alpha_upper_spaces_underscores: /^[A-Z _]+$/,
  alpha_upper_dashes_underscores: /^[A-Z\-_]+$/,
  alnum: /^[a-z0-9]+$/i,
  alnum_spaces: /^[a-z0-9 ]+$/i,
  alnum_dashes: /^[a-z0-9\-]+$/i,
  alnum_underscores: /^[a-z0-9_]+$/i,
  alnum_spaces_underscores: /^[a-z0-9 _]+$/i,
  alnum_dashes_underscores: /^[a-z0-9\-_]+$/i,
  alnum_lower: /^[a-z0-9]+$/,
  alnum_lower_spaces: /^[a-z0-9 ]+$/,
  alnum_lower_dashes: /^[a-z0-9\-]+$/,
  alnum_lower_underscores: /^[a-z0-9_]+$/,
  alnum_lower_spaces_underscores: /^[a-z0-9 _]+$/,
  alnum_lower_dashes_underscores: /^[a-z0-9\-_]+$/,
  alnum_upper: /^[A-Z0-9]+$/,
  alnum_upper_spaces: /^[A-Z0-9 ]+$/,
  alnum_upper_dashes: /^[A-Z0-9\-]+$/,
  alnum_upper_underscores: /^[A-Z0-9_]+$/,
  alnum_upper_spaces_underscores: /^[A-Z0-9 _]+$/,
  alnum_upper_dashes_underscores: /^[A-Z0-9\-_]+$/,
  white_space: /^s+$/g,
  variable: /^[a-z][a-z0-9_]+$/i,
  anything: /.+/,
  md5: /^[a-f0-9]{32}$/i,
  uuid: /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i,
  url: /^(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?\^=%&amp;:~\+#]*[\w\-\@?\^=%&amp;~\+#])?$/i,
  email: /^[_a-z0-9\-"'\/]+(\.[_a-z0-9\-"'\/]+)*@[a-z0-9\-]+(\.[a-z0-9\-]+)*\.(([0-9]{1,3})|([a-z]{2,3})|(aero|coop|info|museum|name|local))$/i,
  password: /^.{6,30}$/
  
}